### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by sharkbruhaha** [bmarian/chat-images#19]
Tried with no other mods enabled and with my mods enabled and doesn't seem to work at all. I am now on 0.7.7 and still doesn't work (tried on 0.7.6 and notta). Enabling the warning on drop and on paste doesn't trigger either, so seems it is not functioning at all.

**Comment by bmarian** [comment]
Please provide the following information:
Os used, browser, system played.

**Comment by bmarian** [comment]
Any errors in the console.

**Comment by sharkbruhaha** [comment]
No, nothing. About the only thing that is happening is that if you drag an image from a website then the url shows up, but that is base feature not of the mod, there is no conversion to an image afterwards.

**Comment by sharkbruhaha** [comment]
herp derp, sorry didn't get email with your first comment.

OS: Windows 10
Browser: Chrome
System played: Cypher System
Foundry version: 0.7.7

**Comment by bmarian** [comment]
everything works as expected for me.

**Comment by sharkbruhaha** [comment]
hm... yea made a fresh world and works, but in my main world it isn't...
I've disabled all my other chat mods, but still notta. Will get back to you if/when I figure out what is the lynch pin. Thanks for checking.

**Comment by sharkbruhaha** [comment]
mmm... found it: https://github.com/Moerill/fvtt-markdown-editor
Any chance of becoming compatible?

**Comment by sharkbruhaha** [comment]
closing as it does work, just incompatible. Will make new ticket for the compatibility ask. Thanks!
