### ISSUE TITLE
Private GM roll not private :)

### ISSUE THREAD

**Issue by Sasmira** [bmarian/chat-images#2]
Hello,

There's a problem with your module Chat images.... when a player roll a private GM roll or Blind GM roll, a bubble say the result ... and if I turn your module off, I have not problem ...  

It's a very good module, I like it but is it possible to fixe that ?

thx for your help !
S.

**Comment by bmarian** [comment]
Oh... ok. Did not test enough with chat bubbles. I'm gonna fix that. I think I know the problem.

**Comment by bmarian** [comment]
Fixed in v1.1.3.
