### ISSUE TITLE
Invalid manifest file

### ISSUE THREAD

**Issue by r-valyar** [bmarian/chat-images#27]
After the last update it seems there is issue with the manifest file when "Check for update" is issued. 

![image](https://user-images.githubusercontent.com/63558984/104818262-358be580-582f-11eb-8080-91114b736360.png)

**Comment by bmarian** [comment]
Please uninstall and reinstall as the manifest location has changed.

**Comment by emirkmo** [comment]
Hey Bmarian I have uninstalled and re-installed and I get the same issue. Only way to fix it is to give the manifest location explicitly. (I used the in foundry search and install)

**Comment by jniezink** [comment]
Sorry, missed the pinned one :)
