### ISSUE TITLE
Image description

### ISSUE THREAD

**Issue by mafamac** [bmarian/chat-images#30]
An idea to improve the module is after a link if I put a "|" could be interpreted as a description for the image. for example, when I share an NPC image could be good to put his name as a description like http://link_image.com/image.jpg|Arabeth. the results:
| image  |
| image  |
| image  |
Arabeth

**Comment by bmarian** [comment]
I think we are getting in the realm of markdown here. And it's something I would probably not implement. But the Foundry chat already supports html so you can achieve this by just writing:

```
<img src="[[URL]]" />
Text
``` 
![image](https://user-images.githubusercontent.com/33843056/148560407-d33501e6-40d8-425a-b2b7-eb529616ee3c.png)


And if you want the same functionality as other images uploaded with my module
```
<div class="chat-images-container">
<img src="[[URL]]" />
</div>
Text
```
![image](https://user-images.githubusercontent.com/33843056/148560675-55c61d56-b098-467e-a6f6-6e01a0c5ed64.png)
