### ISSUE TITLE
Not a valid manifest file

### ISSUE THREAD

**Issue by JokersWyld** [bmarian/chat-images#36]
**Problem**
Unable to update/reinstall.  Receiving error -
Installation failed: Request to: https://github.com/bmarian/chat-images/blob/master/module.json did not provide a valid manifest file.

Tried manually pasting the file location and installing from module search.

**Comment by CrimWolfe** [comment]
So, I was seeing the same, but I did it manually with this link and it is working. https://raw.githubusercontent.com/bmarian/chat-images/master/module.json Hope that helps ya out.

**Comment by JokersWyld** [comment]
I haven't changed anything, but it appears to be working now.  I think the new update process has the new manifest file.
