### ISSUE TITLE
Image file location

### ISSUE THREAD

**Issue by MasudaH** [bmarian/chat-images#37]
Where is the data\uploaded-chat-images folder located? It doesn't seem to be inside Foundry's User Data Path or any child directory. It's also not within any of the AppData subdirectories or the Foundry installation folder.

**Comment by MasudaH** [comment]
It seems the file isn't created automatically. When copying an image (not the image url) into the chat it doesn't seem to require local storage. But dragging an image into the chat prompts an error.

**Comment by bmarian** [comment]
It should create the folder automatically. I will investigate. Thank you for pointing this out.

**Comment by bmarian** [comment]
Fixed with update #2.5.5
