### ISSUE TITLE
Sandbox system bug

### ISSUE THREAD

**Issue by jacksands** [bmarian/chat-images#47]
Hi, first tks for the module! I use it a lot!

Just one issue, clicking on a imagem on chat created by chat image module do not open a preview if using sandbox system.

May you take a look if you can?

tks!

![1](https://user-images.githubusercontent.com/7229143/175387227-7799318b-b787-4493-b4ce-6dd5e3abbfb2.png)

**Comment by bmarian** [comment]
I can't do much about this. The sandbox system messes with how the messages are rendered.

**Comment by bmarian** [comment]
I will give it a shot after I finished the 3.0 version
