### ISSUE TITLE
"Umaintained" Status?

### ISSUE THREAD

**Issue by drober76** [bmarian/chat-images#50]
Foundry is giving me a warning that chat-images is "unmaintained."  Is this because it just works, or is it inactive?  Will it be updated for v10?

**Comment by danil0man** [comment]
Please update this to work with v10. It helps alots

**Comment by orwen89** [comment]
I wonder as well. This module is one of the best modules I use, so thanks for making it work for v9,
I understand that working on a module like this takes a lot of effort @bmarian , I'd  only like to know, whether you plan to update to Foundry v10 compatible (in the near future) or I'm better off look for alternatives? It's ok either way, but the info would be great.

**Comment by bmarian** [comment]
Is the module not working? Did you test it? Because it looks ok to me. Only the version warning

**Comment by orwen89** [comment]
No errors (sadly), but the direct image links doesn't converting to images for some reason.

![chat_images_test](https://user-images.githubusercontent.com/8012611/188715004-a9e8a516-8d3a-4d8d-82da-17b5681c3a3f.jpg)

**Comment by bmarian** [comment]
Everything should be fixed with the latest update
