### ISSUE TITLE
Issue #50 still not working

### ISSUE THREAD

**Issue by danil0man** [bmarian/chat-images#52]
When I copy an image URL it just gives me an empty file. It works if the image is on my pc but not if I copy it from the internet. 
Both Copy Image or Copy Image Adress gives me this
![image](https://user-images.githubusercontent.com/72052103/189500006-6fde05e3-cd0d-47be-a4ec-5c8feb8dbaec.png)
I have updated to 2.5.8
![image](https://user-images.githubusercontent.com/72052103/189500035-c4b43c47-d869-4903-9603-02c8486b8e62.png)

**Comment by danil0man** [comment]
I get this error in the console when I try to copy the image
![image](https://user-images.githubusercontent.com/72052103/189500087-53bca60b-17d3-4b16-8abe-cfbed5dafc7c.png)

**Comment by bmarian** [comment]
what system are you using?

**Comment by danil0man** [comment]
Hello I am using warhammer fantasy
