### ISSUE TITLE
Last Image give error

### ISSUE THREAD

**Issue by danil0man** [bmarian/chat-images#54]
Hello. I have updated to 3.0. When I add the image preview it works,
If I add more than two pictures the last one does not parse into the chat window. I add an example
**Adding only 1 image**
![image](https://user-images.githubusercontent.com/72052103/189913142-58ee03db-bc87-40c4-b3c1-16e9369fb125.png)
Result and error message
![image](https://user-images.githubusercontent.com/72052103/189913256-080d159f-4de8-4034-bf7d-4abbc510635e.png)
![image](https://user-images.githubusercontent.com/72052103/189913436-842b7951-d203-4e3c-85fd-617cdd79234b.png)

**Adding Multiple Images**
![image](https://user-images.githubusercontent.com/72052103/189913577-334c14ec-750c-4fc0-aa93-52b5d9efc45b.png)
Result and error message
![image](https://user-images.githubusercontent.com/72052103/189913752-755b4494-82ff-4bc6-ba50-14389ca8e108.png)
![image](https://user-images.githubusercontent.com/72052103/189913892-eb40c049-53ac-4412-930f-40662cd0b07d.png)

**Comment by bmarian** [comment]
I am unable to reproduce your problem

Do you have other modules installed?
Does this happen when you drag and drop images/ copy from the internet / add from file? It happens with every image you are using?

If you can, provide the name of the images or links to them, and a screenshot of the inspect element tab like so:

![image](https://user-images.githubusercontent.com/33843056/189919869-ae59ae37-0093-4287-a921-7e035b70c2fa.png)

**Comment by danil0man** [comment]
![image](https://user-images.githubusercontent.com/72052103/189923306-4913d525-e083-4b5b-9329-4192072e92ef.png)
Dont know if this help. But it kind of create a ghost tag

**Comment by bmarian** [comment]
It is not supposed to look like this. 
![image](https://user-images.githubusercontent.com/33843056/189924049-71558eb4-355e-49c7-b63a-e485c0569e75.png)

**Comment by bmarian** [comment]
With Table Rolls and Deepflame's Chat Cards installed it is still working for me. 

I am kind off shooting in the dark here, so if you have the patience, you should start disabling modules or use Find The Culprit to find what module is incompatible with CI.

P.S back up your world if you start disabling stuff 😄

**Comment by danil0man** [comment]
Ok. I try my best

**Comment by danil0man** [comment]
I report as soon as I find something

**Comment by danil0man** [comment]
Ok. I found the culprit. Is Image Context from rippers that is giving me the error

**Comment by bmarian** [comment]
I’ll take a look when I get back home, and if I can’t fix it on my end I’ll report it to the creator

**Comment by danil0man** [comment]
and it dont copy images from the system into the chat window

**Comment by bmarian** [comment]
This looks like it's a paid mod. If you bought it, please contact the creator and maybe link them this thread 😄 

Otherwise, I can't do much sorry.
