### ISSUE TITLE
Images are not displayed to players

### ISSUE THREAD

**Issue by Rudruk** [bmarian/chat-images#61]
Hi,
Since one/two weeks, images are not uploaded in the chat but in a black space between the bottom writing DM space and the above system information (attacks, etc).
As a result, images are not displayed to players.

Thanks for fixing.
Ugun

**Comment by bmarian** [comment]
Please provide some images. I don't understand the problem

**Comment by Rudruk** [comment]
Hi Marian,

Please find attached.
I tried with using upload button or simple drag and drop, with button activated or not.

Thanks !
Ugun

De : Marian ***@***.***>
Envoyé le :samedi 1 octobre 2022 17:38
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [bmarian/chat-images] Images are not displayed to players (Issue #61)


Please provide some images. I don't understand the problem

**Comment by bmarian** [comment]
I was asking for an image with the actual problem.

Does your chat look like in the video https://github.com/bmarian/chat-images?
If yes? Just hit enter after adding the images.

**Comment by bmarian** [comment]
I can't see attachments from emails, please respond on github.

**Comment by Rudruk** [comment]
Issue solved :) Thanks for your help !
