### ISSUE TITLE
  Trying to contact bmarian

### ISSUE THREAD

**Issue by pharnb** [bmarian/chat-images#64]
Hi, sorry to contact you like this but I didn't see an email on your profile so I didn't know how else to reach you.  

Are you available to de-archive Sadness Chan and then accept the pull request made by @ClipplerBlood?  He updated the module to be compatible for Foundry v10 but cannot publish the update to Foundry's module repository without your permission (as master) or unless he makes a brand new module (not ideal).  https://github.com/ClipplerBlood/sadness-chan/releases/tag/1.1.9.  You can reply to this issue, or you can find us on Discord, CombatDoctor#1207 or ClipplerBlood#8146.

**Comment by bmarian** [comment]
Hello there, I unarchived the repo, make a PR there please and I'll merge it in the morning. It's like 4AM for me right now 🤣
